### ISSUE TITLE
Typo in comprehension-term-assignment.md

### ISSUE THREAD

**Issue by geirs73** [StyraInc/regal#1200]
In the docs, there is a typo in the configuration options for comprehension-term-assignment, it says comprehension-tail-assignment.

```yaml
rules:
  style:
    comprehension-tail-assignment:
      # one of "error", "warning", "ignore"
      level: error
```

Ref:  `docs/rules/style/comprehension-term-assignment.md`
