### ISSUE TITLE
LSP: ignore config doesn't fully work for some rules

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#1204]
I'm not yet sure what the cause is or why it doesn't happen consistently, but for some rules, like [missing-metadata](https://docs.styra.com/regal/rules/custom/missing-metadata), a configuration like this:

```yaml
rules:
  custom:
    missing-metadata:
      level: error
      ignore:
        files:
          - "*_test.rego"
          - "bundle/example/**"
```

Ignores test files as expected, but **not** files under `bundle/example`. This works fine for `regal lint`, so there seems to be some inconsistency as to how the language server parses the configuration. Obviously the ideal would be if we had only one way of doing this, but either way, they should at least work the same.
