### ISSUE TITLE
Add `regal new config` command to create starter configuration

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#1508]
Without any arguments, this command should identify possible roots and Rego versions used, and save that in a `.regal/config.yaml` in the same directory.

```yaml
project:
  roots:
    - name: policy
      rego-version: 1
    - name: lib
      rego-version: 0
```

For existing projects, it would also save a lot of time to be able to set a level (like `ignore`) on all existing rules where violations have been reported. This is a common (and good!) strategy to start out from a clean state before slowly removing the `ignore` level one rule at the time. If we also saved the number of violations reported in a comment above any rule, that would help with prioritization.

```yaml
rules:
  idiomatic:
    # 4 violations
    use-in-operator:
      level: ignore
  imports:
    # 1 violation
    prefer-package-imports:
      level: ignore
  style:
    # 7 violations
    default-over-else:
      level: ignore
```
