### ISSUE TITLE
Support capabilities feature from OPA

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#212]
> We could even ship with a capabilities config that supported e.g. Gatekeeper, EOPA, and whatever else there is, out of the box. Having to bring that whole JSON file and edit it manually always felt somewhat "low-level" to me. We should look into some easier mechanics for Regal, like allowing capabilities to be defined in the Regal conf.

From https://github.com/StyraInc/regal/issues/211

Adding capabilities via config could look something like:

```yaml
rules: 
  testing:
    test-outside-test-package:
      level: ignore

capabilities:
  from:
    # could be opa, eopa, gatekeeper, or any other known project extending opa
    engine: opa
    version: v0.54.0
  plus:
    builtins:
      - name: ldap.query
        type: function
        decl:
          args:
            - type: string
        result:
          type: object
  minus:
    builtins:
      - name: http.send 
```
We should also accept a `capabilities.json` file from OPA, since some users likely already have one. 
```yaml
capabilities:
  from:
    file: ${project_root}/capabilities.json
```

CLI flags for the most common and quick options would be nice too I supoose, but no hard requirement IMHO.
