### ISSUE TITLE
Add GitLab code quality output format

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#275]
See https://docs.gitlab.com/ee/ci/testing/code_quality.html#implement-a-custom-tool

**Comment by anderseknert** [comment]
Having played around with this, I don't think this would be useful. The code quality report seems to be used merely for informative purposes, and would not fail the build on violations. Better to just run Regal as a job of it's own. If GitLab adds a way to emit annotations from a job at some point, we should revisit this, but I'll close this for now. If you came here looking for how to run Regal in GitLab CI, it's as simple as:

```yaml
regal:
  stage: test
  image:
    # change to whatever version is latest, don't actually use :latest
    name: ghcr.io/styrainc/regal:latest
    entrypoint: [""]
  # change policy/ to where you want Regal to lint
  script: ["regal lint policy/"]
```
