### ISSUE TITLE
Overriding rule configuration requires providing level attribute

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#285]
While I personally prefer explicit configuration, it should be possible to override only attributes of interest, and inherit the `level` attribute from the Regal-provided configuration.
```yaml
rules:
  testing:
    metasyntactic-variable:
      ignore:
        files:
          - "*test.rego"
```

But this configuration will fail with:
```
failed to decode user config from /project/.regal: value of 'level' must be string
```
And that's a bug.
