### ISSUE TITLE
Rule: `unresolved-import`

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#300]
This is requested from time to time in OPA, even as far back as [2017](https://github.com/open-policy-agent/opa/issues/491)! 

How imports are handled is unlikely to change in OPA, but we could certainly be more stringent in Regal. Once #282 has landed, it would be simple to aggregate the imports of all policies, and then have an aggregate rule that "resolves" all imports — i..e checks that there is a corresponding module to map to.

Obviously, we'll need to allow exceptions for dynamic / data imports, which would be easy to do either via configuration:

```yaml
rules:
  custom:
    unresolved-import:
      level: error
      except-imports:
        - data.some.dynamic.stuff
``` 

or an ignore directive, like:

```rego
# regal ignore:require-imports
import data.some.dynamic.stuff
```

Making this a custom rule seems like the best way to me, as I don't think we'll want this enabled by default, and the rule likely will need custom configuration in most repos.
