### ISSUE TITLE
Use .gitignore for filtering

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#336]
Some configuration options to the `ignore` attribute that would be nice additions:

```yaml
ignore:
  # both of these would be true by default
  dot-git-dir: true
  use-git-ignore: true
  files:
    - foo.rego
```

We currently hard code `.git` and `.idea` as we never will want to parse whatever is in there, but exposing these options in config, and using the `.gitignore` file, would be a better approach.

Thanks @srenatus for the idea.
