### ISSUE TITLE
Allow configuration to provide "aggregate directories"

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#340]
Our default behavior for considering aggregate rules is simple — if `regal lint` is invoked to lint a single file, we don't run aggregate rules, and if invoked with more than one file we run the aggregate rules. I think this will be good enough for the majority of use cases, but there are a few scenarios where it won't be:

1. Your Rego files are in the `policy` directory, and you run `regal lint policy/some/sub/directory`
2. You have more than one "policy project" in a single repo, and you want to be able to lint all of them with a single command

In the first scenario, you'll likely want Regal to _not_ run aggregate rules, as the full context of the project is not available. For the next scenario, we have the opposite problem, as running `regal lint .` in the repo root directory would give us "too much context" — aggregates from one project should not affect another project. 

While this could be solved by running `regal lint` on each "project directory" separately:

```
regal lint policy/project1
regal lint policy/project2
regal lint policy/project3
```
I think it would be helpful if we allowed providing this information via configuration:

```yaml
rules:

projects:
  # using objects here as we could potentially want to allow
  # more data on a project at some point
  - directory: policy/project1
  - directory: policy/project2
  - directory: policy/project3
```

This way, you could run `regal lint .` or `regal lint policy` as a single command, while still retaining isolation between projects when collecting aggregates. And in the case of `regal lint policy/project1/some/sub/directory`, we'd know that this is not the context of a full project, and skip the aggregate rules too.

I have not given much thought to naming yet, so suggestions are definitely welcome :)
