### ISSUE TITLE
Adding `line-length` config seems to disable the rule

### ISSUE THREAD

**Issue by anderseknert** [StyraInc/regal#472]
Odd, but I wanted to use the `non-breaking-word-threshold` option today in a repo, but just adding _any_ config for the [line-length](https://docs.styra.com/regal/rules/style/line-length) rule seems to disable it entirely, even if just:

```yaml
rules:
  style:
    line-length:
      level: error
```
